### PR TITLE
Fix for issue_66

### PR DESCRIPTION
**Pull request by ivanlei**
Add a new `full_hash` section. This will only run when explicitly asked for.
It runs the hashing and sig checks on everything on disk.

Probably a tool not in python should be written to do this.

### CODE REVIEW

**Comment by secretsquirrel** [comment]
initial output, running a timed test (still going):
sudo ./osxcollector.py -s full_hash
[ERROR]   <type 'exceptions.UnicodeDecodeError'> [('./osxcollector.py', 972, '_log_file_info_for_directory', 'file_info = _get_file_info(file_path, True)'), ('./osxcollector.py', 298, '_get_file_info', 'signature_chain = CodeSignChecker.get_signature_chain(file_path)'), ('./osxcollector.py', 650, 'get_signature_chain', 'static_code = cls.SecStaticCodeCreateWithPath(file_path)'), ('./osxcollector.py', 488, 'SecStaticCodeCreateWithPath', "file_path = Foundation.NSString.stringWithUTF8String_(file_path.encode(encoding='utf-8', errors='ignore'))")] - {'osxcollector_incident_id': 'osxcollect-2015_01_30-14_55_27', 'osxcollector_section': 'full_hash'}
[ERROR]   <type 'exceptions.UnicodeDecodeError'> [('./osxcollector.py', 972, '_log_file_info_for_directory', 'file_info = _get_file_info(file_path, True)'), ('./osxcollector.py', 298, '_get_file_info', 'signature_chain = CodeSignChecker.get_signature_chain(file_path)'), ('./osxcollector.py', 650, 'get_signature_chain', 'static_code = cls.SecStaticCodeCreateWithPath(file_path)'), ('./osxcollector.py', 488, 'SecStaticCodeCreateWithPath', "file_path = Foundation.NSString.stringWithUTF8String_(file_path.encode(encoding='utf-8', errors='ignore'))")] - {'osxcollector_incident_id': 'osxcollect-2015_01_30-14_55_27', 'osxcollector_section': 'full_hash'}

**Comment by ivanlei** [comment]
Lemme put some more logging around that. I'm guessing it's fancy file name which somehow throw everything to hell.

It won't stop it all from running but it probably breaks some stuff.

**Comment by secretsquirrel** [comment]
Update:
Started: Fri Jan 30 14:55:24 PST 2015
End: 2015-01-30 15:21:08
So less than 30 minutes on a VM.
This error was repeated, same as before, many times (100+):
[ERROR]   <type 'exceptions.UnicodeDecodeError'> [('./osxcollector.py', 972, '_log_file_info_for_directory', 'file_info = _get_file_info(file_path, True)'), ('./osxcollector.py', 298, '_get_file_info', 'signature_chain = CodeSignChecker.get_signature_chain(file_path)'), ('./osxcollector.py', 650, 'get_signature_chain', 'static_code = cls.SecStaticCodeCreateWithPath(file_path)'), ('./osxcollector.py', 488, 'SecStaticCodeCreateWithPath', "file_path = Foundation.NSString.stringWithUTF8String_(file_path.encode(encoding='utf-8', errors='ignore'))")] - {'osxcollector_incident_id': 'osxcollect-2015_01_30-14_55_27', 'osxcollector_section': 'full_hash'}
[ERROR]   <type 'exceptions.UnicodeDecodeError'> [('./osxcollector.py', 972, '_log_file_info_for_directory', 'file_info = _get_file_info(file_path, True)'), ('./osxcollector.py', 298, '_get_file_info', 'signature_chain = CodeSignChecker.get_signature_chain(file_path)'), ('./osxcollector.py', 650, 'get_signature_chain', 'static_code = cls.SecStaticCodeCreateWithPath(file_path)'), ('./osxcollector.py', 488, 'SecStaticCodeCreateWithPath', "file_path = Foundation.NSString.stringWithUTF8String_(file_path.encode(encoding='utf-8', errors='ignore'))")] - {'osxcollector_incident_id': 'osxcollect-2015_01_30-14_55_27', 'osxcollector_section': 'full_hash'}

**Comment by ivanlei** [comment]
Pushed a small fix to remove the errors @secretsquirrel was seeing. Just waiting for Travis CI to complete and then I'll merge the PR.

**Pull request merged**
