### PR TITLE
bumping threat_intel version number to 0.1.9

### PR DESCRIPTION
**Pull request by megancarney**

### CODE REVIEW

**Comment by jjsendor** [comment]
Looks like there are some errors while testing with the new version. Does it work for you locally @megancarney?

**Comment by jjsendor** [comment]
@megancarney I have just checked out the branch locally and tried to run the tests.
On the first attempt it worked just fine:
```
make test
```
But then I have remembered that after changing dependencies tox is fetching the new versions only when running it with `-r`:
```
tox -r
```
and now I can see exactly the same error as in Travis.

**Comment by megancarney** [comment]
Could be a cut-and-paste problem, I never figured out a good way to checkout the threat_intel library from within the osxcollector venv, so I copied my changes back to repo I had checked out. Maybe we should walk through it together?

**Comment by megancarney** [comment]
What's the purpose of the no domains test?

**Comment by jjsendor** [comment]
hehe, good question @megancarney ;)

Well, it was probably sort of a stub for further tests. It is really weird that it tries to call Threat Intel despite no domains being in the JSON.

**Comment by jjsendor** [comment]
Alright, I think I have nailed down what is going on.

Basically `LookupDomainsFilter` is always trying to call `investigate.categorization`, even if the domain list is empty.
That on in its own should not cause any troubles. If you pass empty domain list tot the Categorization API it will just give you an empty JSON object in response (`{}`).

The problem is that this code is trying to call the real API while it doesn't have the real credentials (it uses a [test configuration file](../tree/master/tests/output_filters/data/test_osxcollector_config.yaml)). In that case response from the Categorization API is 403 and this is somehow treated as "no response" in the new version of Threat Intel.

It is quite weird for me that it worked before, as I guess this test was always calling the API endpoint, with no real credentials whatsoever. I am guessing that it was just returning this fake response and it wasn't really causing any problems then.
I feel like adding a check whether the domains (or `iocs`, as it is called there) list is empty before making any calls to Investigate API in [lookup_domains.py](../blob/707e7442da4e0b6bf0c7782237ca16757c802800/osxcollector/output_filters/opendns/lookup_domains.py#L95) should solve the issue.

**Comment by jjsendor** [comment]
Closing this one as I have posted an updated pull request in #102.
(Not sure why GitHub hasn't updated this one when I pushed the changes to the original branch.)

**Pull request closed without merging**
